apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lar-demo
  name: lar-demo
  namespace: nju13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lar-demo
  template:
    metadata:
      labels:
        app: lar-demo
    spec:
      containers:
        - name: lar-demo
          image: harbor.edu.cn/nju13/lar-demo:65
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080
          resources: #基于内存自动扩容
            limits:
              cpu: 200m
            requests: #新增cpu配置
              cpu: 80m  #CPU大小, 1核cpu等于1000m--
      imagePullSecrets: # 本地测试时注销
        - name: docker-harbor-nju13 # 本地测试时注销

---
apiVersion: v1
kind: Service
metadata:
  name: lar-demo
  namespace: nju13
spec:
  ports:
    - port: 8080
  #     nodePort: 31007
      protocol: TCP
  selector:
    app: lar-demo
  type: ClusterIP
