apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lar-demo-hpa
  name: lar-demo-hpa
  namespace: nju13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lar-demo-hpa
  template:
    metadata:
      labels:
        app: lar-demo-hpa
    spec:
      containers:
        - name: lar-demo-hpa
          image: harbor.edu.cn/nju13/lar-demo:70
          ports:
            - containerPort: 8080
          resources: #基于内存自动扩容
            limits:
              cpu: 200m
            requests:
              cpu: 80m
      imagePullSecrets: # 本地测试时注销
        - name: docker-harbor-nju13 # 本地测试时注销

---
apiVersion: v1
kind: Service
metadata:
  name: lar-demo-hpa
  namespace: nju13
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: lar-demo-hpa
  type: ClusterIP
